CREATE TABLE REGISTRO
(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRES VARCHAR(20) not null,
APELLIDOS VARCHAR(20) not null,
CORREO VARCHAR(20) not null,
EMPRESA VARCHAR(20) not null,
CELULAR VARCHAR(10) not null,
CONTRASEÑA VARCHAR(256) not null,
FECHA_NACIMIENTO DATE not null
 )
